{
    "file_information": {
        "file_name": "1,3-Butadiene.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 0.00224865996,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.1118
            ],
            [
                6,
                0.8882
            ]
        ]
    }
}