{
    "file_information": {
        "file_name": "Ammonia.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 0.000718772004,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.177547
            ],
            [
                7,
                0.822453
            ]
        ]
    }
}