{
    "file_information": {
        "file_name": "Barium Fluoride.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 4.8299999,
        "number_of_elements": 2,
        "elements": [
            [
                9,
                0.21672
            ],
            [
                56,
                0.78328
            ]
        ]
    }
}