{
    "file_information": {
        "file_name": "Beryllium Oxide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 3.01,
        "number_of_elements": 2,
        "elements": [
            [
                4,
                0.36032
            ],
            [
                8,
                0.63968
            ]
        ]
    }
}