{
    "file_information": {
        "file_name": "Boron Oxide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 1.812,
        "number_of_elements": 2,
        "elements": [
            [
                5,
                0.310551
            ],
            [
                8,
                0.689449
            ]
        ]
    }
}