{
    "file_information": {
        "file_name": "Butane.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 0.00246455008,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.173408
            ],
            [
                6,
                0.826592
            ]
        ]
    }
}