{
    "file_information": {
        "file_name": "Cadmium Telluride.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 6.1999998,
        "number_of_elements": 2,
        "elements": [
            [
                48,
                0.468356
            ],
            [
                52,
                0.531645
            ]
        ]
    }
}