{
    "file_information": {
        "file_name": "Calcium Fluoride.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 3.1800001,
        "number_of_elements": 2,
        "elements": [
            [
                9,
                0.486659
            ],
            [
                20,
                0.513341
            ]
        ]
    }
}