{
    "file_information": {
        "file_name": "Calcium Oxide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 3.3499999,
        "number_of_elements": 2,
        "elements": [
            [
                8,
                0.285299
            ],
            [
                20,
                0.714701
            ]
        ]
    }
}