{
    "file_information": {
        "file_name": "Carbon Monoxide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 0.00116472004,
        "number_of_elements": 2,
        "elements": [
            [
                6,
                0.428805
            ],
            [
                8,
                0.571195
            ]
        ]
    }
}