{
    "file_information": {
        "file_name": "Carbon Disulfide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 1.261,
        "number_of_elements": 2,
        "elements": [
            [
                6,
                0.157768
            ],
            [
                16,
                0.842232
            ]
        ]
    }
}