{
    "file_information": {
        "file_name": "Cesium Iodide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 4.5100002,
        "number_of_elements": 2,
        "elements": [
            [
                53,
                0.488451
            ],
            [
                55,
                0.511549
            ]
        ]
    }
}