{
    "file_information": {
        "file_name": "Cesium Chloride.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 3.9879999,
        "number_of_elements": 2,
        "elements": [
            [
                17,
                0.210581
            ],
            [
                55,
                0.789419
            ]
        ]
    }
}