{
    "file_information": {
        "file_name": "Cesium Fluoride.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 4.1149998,
        "number_of_elements": 2,
        "elements": [
            [
                9,
                0.125069
            ],
            [
                55,
                0.874931
            ]
        ]
    }
}