{
    "file_information": {
        "file_name": "Copper Alloy (Yellow Brass).comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 8.4700003,
        "number_of_elements": 2,
        "elements": [
            [
                29,
                0.66
            ],
            [
                30,
                0.34
            ]
        ]
    }
}