{
    "file_information": {
        "file_name": "Copper Alloy (Commercial Bronze).comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 8.8000002,
        "number_of_elements": 2,
        "elements": [
            [
                29,
                0.9
            ],
            [
                30,
                0.1
            ]
        ]
    }
}