{
    "file_information": {
        "file_name": "Ferrous Oxide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 5.6999998,
        "number_of_elements": 2,
        "elements": [
            [
                8,
                0.222689
            ],
            [
                26,
                0.777311
            ]
        ]
    }
}