{
    "file_information": {
        "file_name": "Gallium Arsenide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 5.3099999,
        "number_of_elements": 2,
        "elements": [
            [
                31,
                0.482019
            ],
            [
                33,
                0.517981
            ]
        ]
    }
}