{
    "file_information": {
        "file_name": "Gel in Photographic Emulsion (Standard Nuclear).comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 1.2914,
        "number_of_elements": 5,
        "elements": [
            [
                1,
                0.08118
            ],
            [
                6,
                0.41606
            ],
            [
                7,
                0.11124
            ],
            [
                8,
                0.38064
            ],
            [
                16,
                0.01088
            ]
        ]
    }
}