{
    "file_information": {
        "file_name": "Lead Oxide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 9.5299997,
        "number_of_elements": 2,
        "elements": [
            [
                8,
                0.071682
            ],
            [
                82,
                0.928318
            ]
        ]
    }
}