{
    "file_information": {
        "file_name": "Lipid Substitute (EVA-28).comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 0.94999999,
        "number_of_elements": 3,
        "elements": [
            [
                1,
                0.12314
            ],
            [
                6,
                0.772787
            ],
            [
                8,
                0.104073
            ]
        ]
    }
}