{
    "file_information": {
        "file_name": "Lithium Iodide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 3.494,
        "number_of_elements": 2,
        "elements": [
            [
                3,
                0.051858
            ],
            [
                53,
                0.948142
            ]
        ]
    }
}