{
    "file_information": {
        "file_name": "Lithium Hydride.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 0.81999999,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.126797
            ],
            [
                3,
                0.873203
            ]
        ]
    }
}