{
    "file_information": {
        "file_name": "Lithium Fluoride.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 2.635,
        "number_of_elements": 2,
        "elements": [
            [
                3,
                0.267585
            ],
            [
                9,
                0.732415
            ]
        ]
    }
}