{
    "file_information": {
        "file_name": "Mercuric Iodide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 6.3600001,
        "number_of_elements": 2,
        "elements": [
            [
                53,
                0.55856
            ],
            [
                80,
                0.44144
            ]
        ]
    }
}