{
    "file_information": {
        "file_name": "N-Hexane.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 0.00358248991,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.163741
            ],
            [
                6,
                0.836259
            ]
        ]
    }
}