{
    "file_information": {
        "file_name": "N-Hexyne.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 0.00341489003,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.122698
            ],
            [
                6,
                0.877302
            ]
        ]
    }
}