{
    "file_information": {
        "file_name": "N-Heptane (Liquid).comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 0.68375999,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.160937
            ],
            [
                6,
                0.839063
            ]
        ]
    }
}