{
    "file_information": {
        "file_name": "N-Nonane (Liquid).comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 0.71759999,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.157169
            ],
            [
                6,
                0.842831
            ]
        ]
    }
}