{
    "file_information": {
        "file_name": "Napthalene.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 1.154,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.062909
            ],
            [
                6,
                0.937091
            ]
        ]
    }
}