{
    "file_information": {
        "file_name": "Nitrous Oxide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 0.00183094002,
        "number_of_elements": 2,
        "elements": [
            [
                7,
                0.636483
            ],
            [
                8,
                0.363517
            ]
        ]
    }
}