{
    "file_information": {
        "file_name": "Octane.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 0.00474872021,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.158821
            ],
            [
                6,
                0.841179
            ]
        ]
    }
}