{
    "file_information": {
        "file_name": "Photographic Emulsion (Standard Nuclear).comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 3.8150001,
        "number_of_elements": 8,
        "elements": [
            [
                1,
                0.0141
            ],
            [
                6,
                0.072261
            ],
            [
                7,
                0.01932
            ],
            [
                8,
                0.066101
            ],
            [
                16,
                0.00189
            ],
            [
                35,
                0.349103
            ],
            [
                47,
                0.474105
            ],
            [
                53,
                0.00312
            ]
        ]
    }
}