{
    "file_information": {
        "file_name": "Photographic Emulsion, Silverhalidesin (Standard Nuclear).comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 6.4699998,
        "number_of_elements": 3,
        "elements": [
            [
                35,
                0.422895
            ],
            [
                47,
                0.573748
            ],
            [
                53,
                0.003357
            ]
        ]
    }
}