{
    "file_information": {
        "file_name": "Plastic Scintillator (Vinyltoluene-based).comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 1.0319999,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.085
            ],
            [
                6,
                0.915
            ]
        ]
    }
}