{
    "file_information": {
        "file_name": "Polystyrene.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 1.0599999,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.077418
            ],
            [
                6,
                0.922582
            ]
        ]
    }
}