{
    "file_information": {
        "file_name": "Potassium Iodide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 3.1300001,
        "number_of_elements": 2,
        "elements": [
            [
                19,
                0.235528
            ],
            [
                53,
                0.764472
            ]
        ]
    }
}