{
    "file_information": {
        "file_name": "Propane (Liquid).comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 0.51999998,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.182855
            ],
            [
                6,
                0.817145
            ]
        ]
    }
}