{
    "file_information": {
        "file_name": "Silicon Dioxide (Quartz).comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 2.6500001,
        "number_of_elements": 2,
        "elements": [
            [
                8,
                0.532565
            ],
            [
                14,
                0.467435
            ]
        ]
    }
}