{
    "file_information": {
        "file_name": "Silicon Nitride.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 3.4400001,
        "number_of_elements": 2,
        "elements": [
            [
                7,
                0.399383
            ],
            [
                14,
                0.600617
            ]
        ]
    }
}