{
    "file_information": {
        "file_name": "Silver Chloride.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 5.5599999,
        "number_of_elements": 2,
        "elements": [
            [
                17,
                0.247368
            ],
            [
                47,
                0.752632
            ]
        ]
    }
}