{
    "file_information": {
        "file_name": "Silver Iodide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 5.6799998,
        "number_of_elements": 2,
        "elements": [
            [
                47,
                0.459458
            ],
            [
                53,
                0.540542
            ]
        ]
    }
}