{
    "file_information": {
        "file_name": "Sodium Monoxide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 2.27,
        "number_of_elements": 2,
        "elements": [
            [
                8,
                0.258143
            ],
            [
                11,
                0.741857
            ]
        ]
    }
}