{
    "file_information": {
        "file_name": "Sodium Chloride.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 2.165,
        "number_of_elements": 2,
        "elements": [
            [
                11,
                0.393372
            ],
            [
                17,
                0.606628
            ]
        ]
    }
}