{
    "file_information": {
        "file_name": "Solder Soft (40-60).comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 8.5200005,
        "number_of_elements": 2,
        "elements": [
            [
                50,
                0.6
            ],
            [
                82,
                0.4
            ]
        ]
    }
}