{
    "file_information": {
        "file_name": "Solder Soft (67-33).comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 9.5799999,
        "number_of_elements": 2,
        "elements": [
            [
                50,
                0.33
            ],
            [
                82,
                0.67
            ]
        ]
    }
}