{
    "file_information": {
        "file_name": "Solder Plumber (50-50).comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 8.8900003,
        "number_of_elements": 2,
        "elements": [
            [
                50,
                0.5
            ],
            [
                82,
                0.5
            ]
        ]
    }
}