{
    "file_information": {
        "file_name": "Teflon.comp",
        "file_type": "matl_def",
        "spekpy_version": "2.0.6",
        "comment": "Copy of the Polytetrafluoroethylene (Teflon).comp file"
    },
    "composition": {
        "density": 2.25,
        "number_of_elements": 2,
        "elements": [
            [
                6,
                0.240183
            ],
            [
                9,
                0.759818
            ]
        ]
    }
}
