{
    "file_information": {
        "file_name": "Tetrachloroethylene.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 1.625,
        "number_of_elements": 2,
        "elements": [
            [
                6,
                0.144856
            ],
            [
                17,
                0.855144
            ]
        ]
    }
}