{
    "file_information": {
        "file_name": "Thalliumchloride.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 7.0040002,
        "number_of_elements": 2,
        "elements": [
            [
                17,
                0.147822
            ],
            [
                81,
                0.852178
            ]
        ]
    }
}