{
    "file_information": {
        "file_name": "Titanium Dioxide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 4.2600002,
        "number_of_elements": 2,
        "elements": [
            [
                8,
                0.400592
            ],
            [
                22,
                0.599408
            ]
        ]
    }
}