{
    "file_information": {
        "file_name": "Toluene.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 0.86690003,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.08751
            ],
            [
                6,
                0.91249
            ]
        ]
    }
}