{
    "file_information": {
        "file_name": "Uranium Dicarbide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 11.28,
        "number_of_elements": 2,
        "elements": [
            [
                6,
                0.091669
            ],
            [
                92,
                0.908331
            ]
        ]
    }
}