{
    "file_information": {
        "file_name": "Uranium Oxide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 10.96,
        "number_of_elements": 2,
        "elements": [
            [
                8,
                0.118502
            ],
            [
                92,
                0.881498
            ]
        ]
    }
}