{
    "file_information": {
        "file_name": "Water, Liquid 75.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 1.0,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.111894
            ],
            [
                8,
                0.888106
            ]
        ]
    }
}