{
    "file_information": {
        "file_name": "Water.comp",
        "file_type": "matl_def",
        "spekpy_version": "2.0.6",
        "comment": "Copy of the Water, Liquid.comp file"
    },
    "composition": {
        "density": 1.0,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.111894
            ],
            [
                8,
                0.888106
            ]
        ]
    }
}
