{
    "file_information": {
        "file_name": "Xylene.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 0.87,
        "number_of_elements": 2,
        "elements": [
            [
                1,
                0.094935
            ],
            [
                6,
                0.905065
            ]
        ]
    }
}