{
    "file_information": {
        "file_name": "Zinc Sulfide.comp",
        "file_type": "matl_def",
        "spekpy_version": "0.0.3",
        "comment": "Material definition from PEGS4 (EGS-NRC)"
    },
    "composition": {
        "density": 4.1020002,
        "number_of_elements": 2,
        "elements": [
            [
                16,
                0.329023
            ],
            [
                30,
                0.670977
            ]
        ]
    }
}